/**
 * Copyright (c) 2025 Bivex
 *
 * Author: Bivex
 * Available for contact via email: support@b-b.top
 * For up-to-date contact information:
 * https://github.com/bivex
 *
 * Created: 2025-12-23T06:13:29
 * Last Updated: 2025-12-23T07:55:17
 *
 * Licensed under the MIT License.
 * Commercial licensing available upon request.
 */

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';

import { SpotlightInitializer } from './SpotlightInitializer';
import { ThemeWrapper } from './ThemeWrapper';
import './globals.css';
import '@radix-ui/themes/styles.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next.js App',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SpotlightInitializer />
        <ThemeWrapper>{children}</ThemeWrapper>
      </body>
    </html>
  );
}
